using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BIA.Entity.DB_Model
{
    /// <summary>
    /// For recode all api activities
    /// </summary>
    public class ApiRequestLog
    {
        /// <summary>
        /// Autogenerated log activity unique id
        /// </summary>
        [Key]
        public long request_log_id { get; set; }
        /// <summary>
        /// loginprovider contains Log In provider kew as a DB session value
        /// </summary>

        [StringLength(128)]
        public string loginprovider { get; set; } = string.Empty;
        /// <summary>
        /// Accessed method name
        /// </summary>

        public string methode_name { get; set; } = string.Empty;
        /// <summary>
        /// request_json contains Json request body
        /// </summary>
        public string request_json { get; set; } = string.Empty;
        /// <summary>
        /// response_json contains Json response body
        /// </summary>
        public string response_json { get; set; } = string.Empty;
        /// <summary>
        /// Request DataTime
        /// </summary>

        public DateTime request_time { get; set; }

    }
}
