INSERT ALL
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:AllowActiveDirectoryUser', 'false', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:AllowAPILoggin', 'true', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:AllowSignalRLoggin', 'true', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:InvalidUserCridential', 'Invalid User Credentials!', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:ValidAccessToken', 'Security token is valid.', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:IsEligibleAES', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:InvalidUserName', 'Invalid username!', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:InvalidSecurityToken', 'Invalid security token!', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:UserValidted', 'User Successfully Validated.', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:UserNotFound', 'User not found!', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:dedicated_Ac_Id', '255,245', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:dedicated_Ac_Id_TOS', '255,245,265,275', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:number_category', 'N', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:AccessTokenFormatV2', '{0},uid:{1},uname:{2},dc:{3},deviceId:{4},random:{5}', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:AccessTokenFormat', '{0},uid:{1},uname:{2},dc:{3},deviceId:{4}', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:B2BtoB2CTwoPaertyValidationOTPNote', 'Optional3: OTP', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:LogDirectory', 'D:/TextLog/', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:dbssBaseUri', 'mpqcZO2BRAdPgF8nxGVzOqyQBLjugVWjZJa3QziQpEc=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:CreateCustomerRetry', '3', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:tokenServiceKey', 'ky9nxeTcOMUm7wzLU2EMYlJOZZfZSoAq1mLc6x6KIHbA6iMz0YUayVfdXUPmQtny', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:dmsBaseUrl', 'kZkqpUx3PQ8+NxLHnLnYQCvs2hdfXlABxDpJO/p2QRTYS0Qcu9mL1eoBf4DcnGVr', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:userName', 'dcAKE3mzXzGaCXdABGt63Q==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:dms_pas', 'dcAKE3mzXzGaCXdABGt63Q==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_code_prepaid', 'MMSTS,RYZ1001', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_code_Postpaid', 'PRFREG', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_category_prepaid', 'Prepaid,ryz-prepaid', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_category_postpaid', 'Postpaid', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_category_simReplacment', 'Swap Sim,Non Sim', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_code_simReplacment', 'SIMSWAP,EV_SIM_SWAP,RYZ1001', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:ChannelId', '1,7,4,5,6,8,9,10', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:ChannelStockId', '16,32,4,5,31,33,35,36', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:ChannelStockIdDefault', '1000', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:JWETLoginProvider', '33ff21f224f0ed4ab2c2bc2295f', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:RetailerBaseAPI', 'pKz8WFvPlMbcfLWiB4RmY8eVK7lgkGxylPRggJFBO05yZ9bRMx04Wveka2F7oVJlU9lrFURtfknykM3TM4/4tA==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:addMinutesForJWET', '2', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:substarctMinutesForJWET', '-5', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:GeofencingDistance', '100', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:GeofencingDistanceCalculateEnable', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:biometricRetUserName', 'rILIo0KwrWDkGANZ9OnVZKosOhKEmTSuWr2+JxIBpG8=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:biometricRetPas', 'bPmW1mBncjP3YfemiOyZr+8EDthEHsyEJ9ICUanFfZuTglsOPOY9w4KUbxSmn/Fu', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:UnobtrusiveJavaScriptEnabled', 'true', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:UserEmailRequired', 'false', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:webpages:Enabled', 'false', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:webpages:Version', '3.0.0.0', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:user_Name', 'retaileruser', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:rso_user_Name', 'fjjdLQJUisW7WLZvibJHDw==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:rso_app_pas', '204960A749BEC27B788270C756245B48D68F8108DCB3E9F56ED0E33D841E9E9A6130B1A447E30B33F30D8544F6BAFA99B1D8F23589DAB07D7276A761DB469BA9', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:complaint_type', 'Raise Complaint to RSO', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:complaint_title', 'Issues from Biometric App', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:preferred_level', 'RSO', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:preferred_level_name', 'Preferred RSO', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:preferrred_level_contact', '01900000000', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:RSOBaseAPI', 'kZkqpUx3PQ8+NxLHnLnYQCvs2hdfXlABxDpJO/p2QRRoigi3Sxuuby5XagcJQNOXeR6w7ktngET34AllXZo1nWKW+JlIJl3fi3HQEGw5CPOfRBldNZ3Oq30/L9Td/9fHQMZhnduBRf4UsG9a1nj/9A==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:sigleSourceAPI', 'AEo9Y4ewM75PQYfqhR12cdy5h/j2Ihln5ha1fCGq6PmCnXoa0xA8RizPSbAJkc6rKR14aUMZd9guvlQsjjUe0aenwADX42xZHu3uuhcYeJg=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:single_source_userName', 'przxY3KS9SgN7UzQxhQpWQ==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:single_source_pas', 'zhCnqwzLh75rj2T7eZjXxA==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:cyn_cherished_filter_allow', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:single_source_active_message', 'Failed (single source). Number already activated. Raise complaint', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:BP_DeviceLatlonNot_Found', 'Latitude or Longitude not found! Please enable device GPS.', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:RetLatLonNotFound', 'Retailer latitude and longitude are not found!', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:CrossesTheArea', 'User crosses the max allowed distance from Retailer - (Distance:', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:is_bts_show', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:BalanceCheckURL', 'NniBnbFR+A/o4z5a8mBz6X5TF53Lw13SiC8xHgu0LzXZXDzx55ZSlek6/Sg01NIv', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:BalanceCheckQueryString', 'cdwfn9skOeKRbk6om1yueK+5F8FOd21UtRS4YUiJFLfdZOzF00isL8nMVrXs89x/jYBdn47BAe/uErNpNhdRKd7qj+ozeH/NGxea8ykv5xLzTQVVMYTc6f8eYk12tzYlwNt9mJBVAA8dozihgSYO9obyfmxjOebTln760jUrAyI=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:BalanceCheckBody', 'FWbdvFoosRtjFBvT1udnocv2UYgVFn/hPtIWbu7h8g3SmT0z6RhwPXBe3YwksMIF/P385zF+U6MYFo5Y0b83LYgLpvBXRZmZcuDr/a2V7ZAh5bHH2XYu3O4gSsy/Gmn5p/HJ9HuMzvpxqM0UGLcXIkh4JNttcks/7bfYSqEk8GU=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:FTRRequestType', 'products', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:FTRRequestChannel', 'RESELLER', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:FTRRequestID', '90004', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:IsRetailerAppCore', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:AirBaseUrl', 'YoNJ5Kweg/FLHRlwVva5MIS5KJNZ1O9hIhfTXyfL9yE=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:AirUserName', 'AoWY1LP4HS9knjaLFkh+Cw==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:AirCred', 'zLyH4DcY3Vt9eYxSBLLptH+LFZu0CG3Ncl4jStY8CsM=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:originNodeType', 'EXT', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:subscriberNumberNAI', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:negotiatedCapabilities', '536871492', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:FTRExpairationMinute', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:AirAuthToken', 'cmVzZWxsZXJhcHBkdW86ZHVvcmVzZWxsZXJhcHBAMTIzNA==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:FPDefaultScore', '60', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:isFtrFeatureOn', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:is_esafValidationNeed', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:eShopBaseUrl', 'uynR6NEMEIcy5LUrkWvFGrVrOV5Mcn0nYMZ6Od6qMxs=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:eShopCredential', 'h9llm9h7LOGg9/tEJbSI2pRJtzrjs+vDYNUFDiXN44Q=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:p_code_starTrek_prepaid', 'RYZ1001', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:p_code_starTrek_prepaid_esim', 'RYZ1001', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_category_StarTrekPrepaid', 'Prepaid', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_category_StarTrekPrepaid_esim', 'Esim', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:session_message', 'User is not exist in session, Please relogin and try again!', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:pa_message', 'OTP has been sent to Retailer''s transaction mobile number.', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:is_ryze_stock_allow', '0', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:default_category', 'S1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:cherish_categories', 'S1,S2,S3,G1,G2,G3', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:adapterBaseURL', 'AEo9Y4ewM75PQYfqhR12cdy5h/j2Ihln5ha1fCGq6PlpLVDigM/Hpm3kTO7mZUaf', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:adapter_user', '/0L7xTd3r51rkH42JOdOBQ==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:adapter_pas', 'CBFcbpXYWPlW86EsGKqTZA==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:stocksNotAllowForRyze', '16,4,5,35,0', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_code_cherish', 'MMSTS', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_category_cherish', 'Prepaid', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_code_cherish_postpaid', 'MMSTS', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_category_cherish_postpaid', 'Prepaid', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_code_cherish_esim', 'MMSTS', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_category_cherish_esim', 'Prepaid', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_code__startrek_cherish', 'MMSTS', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_category_startrek_cherish', 'Prepaid', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_code_startrek_cherish_esim', 'MMSTS', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:product_category__startrek_cherish_esim', 'Prepaid', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:TOSValidationTime', '0', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:IccCheckUserName', 'Dj1Czcpcj2rcrYN+SQuZZw==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:IccCheckPassword', 'iE6V56Az6O7PGEntjju1XA==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:EVTransactionDetailsURL', 'NniBnbFR+A/o4z5a8mBz6X5TF53Lw13SiC8xHgu0LzVoHolQPaGRXoHmd4DFu+4XYVH1zRe9sfb3boc996W5j+73qFPhzTFdexAFI6gZPFqh1q6YpGbTlifM5pVRkWwK+Xw+LZVZvPJ8M+nSp5GzoBHVDst4sPUNA76WZFhLvxDaos2WQu4VPiJLIsJ4Q1+e8rDVCSAnPmjSaISHu4mQWy4mKDQpTICbEHV56jMJTP0=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DMSSIMValidationAPI', 'kZkqpUx3PQ8+NxLHnLnYQCvs2hdfXlABxDpJO/p2QRSdk65C2e7V5LZg9z4JdwiH3zYh3mZjGPqh5WRLHH/X7Q==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:TOSBypassTimeInMinutes', '30', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:ActiveNumberCountEligibility', 'RESELLER', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:sessionExpirationInMinutes', '1440', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:dbssSessionExpirationInMinutes', '30', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:ExternalLoginExiprationTime', '30', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:SIMProduct', 'MMSTD', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:IsRecycleBaseCheckingNeeded', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:ConfigMarker', 'DEVELOPMENT_CONFIG', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:is_cbvmp_phase2', '1', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPEBaseUrl', 'isUMwD87PrVIfT8k2UWb0Bd9YFa9MA5xL2z+MZlSDl4Non041qm1VO/rK9hUFt+q', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPEClientID', 'pokTceyOohqcc/XbUF+Blg==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPEClientSecret', 'iE6V56Az6O7PGEntjju1XA==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPEChannel', 'JDQ7hjkjqApuP+E+7VKkTQ==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPEClientCred', '+2eXIaEMzcWMoRE5otXmznapogQJFKOHpnhSvSsxvz4=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPEOrderType', 'FWA_NEW_CONNECTION', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPELeadListEndPoint', '32eSZa2nwcdwd6dVoYFq7w==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPELeadDetailsEndPoint', '32eSZa2nwcdwd6dVoYFq7w==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPEUpdateOrderEndPoint', '32eSZa2nwcdwd6dVoYFq7w==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPEImeiUpdateEndPoint', 'fo8yqK3C1mPvUrupaetumlm34idq4PLU0NJr3OekydWuOw2PBVtMHxX3RCUyMfkX', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPESendPaymentLinkEndPoint', 'cb3KnlhtRS3Y4SDuw1/yPsYegBh1hMeRTQTr/s6+fXemUn+/FIyTF4coFPE6VeAL', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:DPELoginEndPoint', 'Mv/D2WzRy0VcbmHUw8rqos5Enp3DEvSOeQwUoVd51y8=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:LeadPreloadAPIendPoint', 'jF8AbPD8X6f8y8ZyzQWXpAaqXrRnZZG/fC4/sEZue+U=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:xchannel', 'FWA', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettings:ReferladAPIendPoint', 'QRetJKB+vaVIuHo70cVYwA==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'SessionKeysJwetAES:EncryptKey', 'Jkb/mQ67MGKKyEusXcp0v8pwpFPqsiJK887PSYWPIPpqhBcOG0xmaGGCM7/OTIP/', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'SessionKeysJwetAES:SignKey', 'FFwTxIk7u2nuzDieKNuqUH0NydlbfbPyLcPfxDZMKcqdYahAfaRwOFdk9SSJkNwRMNWfuMLRj+CTdi/c61dfYMyBt8lh+mgjfocXT1c/+L+18/QAqveZwfcVRmv+RLIom/3LW9d0Da8+kmtfYqethEP3vkldB/54tNT8zqHSfdfdGKo4p49AUO8wuiXo8Tmq', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'SessionKeysJwetAES:aes', 'Lh98YwuIn1zxt3FPWTZFlAa14EHdPAdN9FaZ9RQWihc=', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'SessionKeysJwetAES:aes_iv', 'vFdnWolsAyO7kCfWuyrnqg==', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'LogPaths:windows', 'E:\Logs\', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'LogPaths:linux', '/app/log/applicationLogs', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'HttpClientSettings:TimeoutSeconds', '300', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'HttpClientSettings:ConnectTimeoutSeconds', '30', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'HttpClientSettings:RetryCount', '3', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettingsKeys:WWWRootPath', 'DBSSBI', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AppSettingsKeys:ApplicationTitle', 'DBSSBI', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'PathBase', '/DBSSBI', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'AllowedHosts', '*', 1)
    INTO BIA_SETTINGS (ENVIRONMENT, CONFIG_KEY, CONFIG_VALUE, IS_ACTIVE) VALUES ('Development', 'DOTNET_GCLog', 'true', 1)
SELECT * FROM dual;
