<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<Import Project="../SharedProjectFile.proj" />

  <ItemGroup>
    <Compile Remove="BLLInterfaces\**" />
    <EmbeddedResource Remove="BLLInterfaces\**" />
    <None Remove="BLLInterfaces\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BIA.DAL\BIA.DAL.csproj" />
    <ProjectReference Include="..\BIA.Entity\BIA.Entity.csproj" />
  </ItemGroup>

</Project>
